In [2]:
import numpy as np

All number are taken from: https://arxiv.org/pdf/1909.12524.pdf

In [3]:
parName = ['rho2', 'R1', 'R2']
parVal = np.array([1.122, 1.270, 0.852])
parSig = np.array([0.024, 0.026, 0.018])

In [4]:
a = np.zeros((3,3))
a[0, 1] = 0.566
a[0, 2] = -0.824
a[1, 2] = -0.715

corrM = a + a.T + np.identity(3)
print corrM

[[ 1.     0.566 -0.824]
 [ 0.566  1.    -0.715]
 [-0.824 -0.715  1.   ]]


In [5]:
covM = np.atleast_2d(parSig).T * corrM * parSig
print covM

[[ 0.000576    0.00035318 -0.00035597]
 [ 0.00035318  0.000676   -0.00033462]
 [-0.00035597 -0.00033462  0.000324  ]]


In [6]:
eigVal, eigVec = np.linalg.eig(covM)

The normalized (unit “length”) eigenvectors, such that the column v[:,i] is the eigenvector corresponding to the eigenvalue w[i].

In [7]:
eigSig = np.sqrt(eigVal)

In [12]:
for i in range(eigSig.shape[0]):
    print 'eigSigma: {:.3f}'.format(eigSig[i])
    print 'eigVect: {:.3f}, {:.3f}, {:.3f}'.format(*eigVec[:, i])
    a = str(np.column_stack((eigSig[i]*eigVec[:, i], -eigSig[i]*eigVec[:, i])))
    print a.replace('\n', ',').replace('[', '{').replace(']', '}')
    print '\n'

eigSigma: 0.035
eigVect: -0.597, -0.651, 0.469
{{-0.02102485  0.02102485}, {-0.02293032  0.02293032}, { 0.01652843 -0.01652843}}


eigSigma: 0.017
eigVect: -0.664, 0.729, 0.167
{{-0.01105955  0.01105955}, { 0.01215074 -0.01215074}, { 0.00278883 -0.00278883}}


eigSigma: 0.008
eigVect: 0.451, 0.211, 0.867
{{ 0.00341205 -0.00341205}, { 0.00159999 -0.00159999}, { 0.00655998 -0.00655998}}


