In [2]:
import numpy as np

# CLN

All number are taken from: https://arxiv.org/pdf/1909.12524.pdf

In [2]:
parName = ['rho2', 'R1', 'R2']
parVal = np.array([1.122, 1.270, 0.852])
parSig = np.array([0.024, 0.026, 0.018])

In [3]:
a = np.zeros((3,3))
a[0, 1] = 0.566
a[0, 2] = -0.824
a[1, 2] = -0.715

corrM = a + a.T + np.identity(3)
print corrM

[[ 1.     0.566 -0.824]
 [ 0.566  1.    -0.715]
 [-0.824 -0.715  1.   ]]


In [4]:
covM = np.atleast_2d(parSig).T * corrM * parSig
print covM

[[ 0.000576    0.00035318 -0.00035597]
 [ 0.00035318  0.000676   -0.00033462]
 [-0.00035597 -0.00033462  0.000324  ]]


In [5]:
eigVal, eigVec = np.linalg.eig(covM)

The normalized (unit “length”) eigenvectors, such that the column v[:,i] is the eigenvector corresponding to the eigenvalue w[i].

In [6]:
eigSig = np.sqrt(eigVal)

In [7]:
for i in range(eigSig.shape[0]):
    print 'eigSigma: {:.3f}'.format(eigSig[i])
    print 'eigVect: {:.3f}, {:.3f}, {:.3f}'.format(*eigVec[:, i])
    a = str(np.column_stack((eigSig[i]*eigVec[:, i], -eigSig[i]*eigVec[:, i])))
    print a.replace('\n', ',').replace('[', '{').replace(']', '}')
    print '\n'

eigSigma: 0.035
eigVect: -0.597, -0.651, 0.469
{{-0.02102485  0.02102485}, {-0.02293032  0.02293032}, { 0.01652843 -0.01652843}}


eigSigma: 0.017
eigVect: -0.664, 0.729, 0.167
{{-0.01105955  0.01105955}, { 0.01215074 -0.01215074}, { 0.00278883 -0.00278883}}


eigSigma: 0.008
eigVect: 0.451, 0.211, 0.867
{{ 0.00341205 -0.00341205}, { 0.00159999 -0.00159999}, { 0.00655998 -0.00655998}}




In [8]:
for i in range(eigSig.shape[0]):
    a = np.column_stack((eigSig[i]*eigVec[:, i], -eigSig[i]*eigVec[:, i]))
    s = '{'
    for l, h in a:
        s += '{{ {:.4f}, {:.4f}}}, '.format(l, h)
    s += ' {0, 0}},'
    print s

{{ -0.0210, 0.0210}, { -0.0229, 0.0229}, { 0.0165, -0.0165},  {0, 0}},
{{ -0.0111, 0.0111}, { 0.0122, -0.0122}, { 0.0028, -0.0028},  {0, 0}},
{{ 0.0034, -0.0034}, { 0.0016, -0.0016}, { 0.0066, -0.0066},  {0, 0}},


In [9]:
for i in range(eigSig.shape[0]):
    a = np.column_stack((2*eigSig[i]*eigVec[:, i], -2*eigSig[i]*eigVec[:, i]))
    s = '{'
    for l, h in a:
        s += '{{ {:.4f}, {:.4f}}}, '.format(l, h)
    s += ' {0, 0}},'
    print s

{{ -0.0420, 0.0420}, { -0.0459, 0.0459}, { 0.0331, -0.0331},  {0, 0}},
{{ -0.0221, 0.0221}, { 0.0243, -0.0243}, { 0.0056, -0.0056},  {0, 0}},
{{ 0.0068, -0.0068}, { 0.0032, -0.0032}, { 0.0131, -0.0131},  {0, 0}},


# BLPR

All references form: arXiv:1703.05330v4

Using scheme NoL+SR (No Lattice QCD, Yes QCD sum rules)

In [10]:
# RhoSq, chi2(1), chi2(1)prime, chi3(1)prime, eta(1), eta(1)prime, V20
parName = ['RhoSq','chi21','chi2p','chi3p','eta1','etap','dV20']
parVal = np.array([1.19, -0.06, -0.00, 0.04, 0.35, -0.11, 0.])
parSig = np.array([0.08, 0.02, 0.02, 0.02, 0.14, 0.18, 0.0001])

In [11]:
a = np.zeros((len(parName),len(parName)))
a[0, 1] = -0.15
a[0, 2] = -0.07
a[0, 3] = 0.57
a[0, 4] = 0.44
a[0, 5] = -0.11

a[1, 2] = -0.02
a[1, 3] = 0.07
a[1, 4] = -0.15
a[1, 5] = -0.09

a[2, 3] = 0.03
a[2, 4] = -0.07
a[2, 5] = -0.05

a[3, 4] = 0.17
a[3, 5] = 0.16

a[4, 5] = -0.40

corrM = a + a.T + np.identity(len(parName))
print corrM

[[ 1.   -0.15 -0.07  0.57  0.44 -0.11  0.  ]
 [-0.15  1.   -0.02  0.07 -0.15 -0.09  0.  ]
 [-0.07 -0.02  1.    0.03 -0.07 -0.05  0.  ]
 [ 0.57  0.07  0.03  1.    0.17  0.16  0.  ]
 [ 0.44 -0.15 -0.07  0.17  1.   -0.4   0.  ]
 [-0.11 -0.09 -0.05  0.16 -0.4   1.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    1.  ]]


In [12]:
covM = np.atleast_2d(parSig).T * corrM * parSig
# print covM

In [13]:
eigVal, eigVec = np.linalg.eig(covM)
eigSig = np.sqrt(eigVal)

In [14]:
for i in range(eigSig.shape[0]):
    print 'eigSigma: {:.3f}'.format(eigSig[i])
    print 'eigVect: {:.3f}, {:.3f}, {:.3f}'.format(*eigVec[:, i])
    a = str(np.column_stack((eigSig[i]*eigVec[:, i], -eigSig[i]*eigVec[:, i])))
    a = a.replace('\n', ',').replace('[', '{').replace(']', '}')
    i = 0
    while i < len(a):
        if a[i].isdigit():
            if a[i+1] == ' ':
                a = a[:i+1] + ',' + a[i+1:]
                i += 2
            else:
                i += 1
        else:
            i += 1
    print a+','
    print '\n'

eigSigma: 0.196
eigVect: 0.119, 0.001, 0.001
{{ 0.02322283, -0.02322283}, { 0.00022429, -0.00022429}, { 0.00023267, -0.00023267}, {-0.00079148,  0.00079148}, { 0.09664184, -0.09664184}, {-0.16885149,  0.16885149}, { 0.         -0.        }},


eigSigma: 0.124
eigVect: -0.349, 0.038, 0.019
{{-0.04345272,  0.04345272}, { 0.00474643, -0.00474643}, { 0.00233232, -0.00233232}, {-0.00809314,  0.00809314}, {-0.09813503,  0.09813503}, {-0.06209618,  0.06209618}, { 0.         -0.        }},


eigSigma: 0.069
eigVect: 0.916, -0.008, -0.003
{{ 0.06298508, -0.06298508}, {-0.00056467,  0.00056467}, {-0.00022681,  0.00022681}, { 0.00975046, -0.00975046}, {-0.02509061,  0.02509061}, {-0.00574474,  0.00574474}, { 0.         -0.        }},


eigSigma: 0.014
eigVect: 0.148, 0.395, 0.196
{{ 0.002127,   -0.002127,  }, { 0.00565397, -0.00565397}, { 0.00281448, -0.00281448}, {-0.01267561,  0.01267561}, { 0.0001571,  -0.0001571, }, { 0.00045325, -0.00045325}, { 0.         -0.        }},


eigSigma: 0.020
eig

In [15]:
for i in range(eigSig.shape[0]):
    a = np.column_stack((2*eigSig[i]*eigVec[:, i], -2*eigSig[i]*eigVec[:, i]))
    s = '{'
    for l, h in a:
        s += '{{ {:.4f}, {:.4f}}}, '.format(l, h)
    s += ' {0, 0}},'
    print s

{{ 0.0464, -0.0464}, { 0.0004, -0.0004}, { 0.0005, -0.0005}, { -0.0016, 0.0016}, { 0.1933, -0.1933}, { -0.3377, 0.3377}, { 0.0000, -0.0000},  {0, 0}},
{{ -0.0869, 0.0869}, { 0.0095, -0.0095}, { 0.0047, -0.0047}, { -0.0162, 0.0162}, { -0.1963, 0.1963}, { -0.1242, 0.1242}, { 0.0000, -0.0000},  {0, 0}},
{{ 0.1260, -0.1260}, { -0.0011, 0.0011}, { -0.0005, 0.0005}, { 0.0195, -0.0195}, { -0.0502, 0.0502}, { -0.0115, 0.0115}, { 0.0000, -0.0000},  {0, 0}},
{{ 0.0043, -0.0043}, { 0.0113, -0.0113}, { 0.0056, -0.0056}, { -0.0254, 0.0254}, { 0.0003, -0.0003}, { 0.0009, -0.0009}, { 0.0000, -0.0000},  {0, 0}},
{{ -0.0015, 0.0015}, { 0.0129, -0.0129}, { 0.0354, -0.0354}, { 0.0134, -0.0134}, { 0.0008, -0.0008}, { 0.0003, -0.0003}, { 0.0000, -0.0000},  {0, 0}},
{{ 0.0012, -0.0012}, { -0.0349, 0.0349}, { 0.0171, -0.0171}, { -0.0116, 0.0116}, { -0.0007, 0.0007}, { -0.0002, 0.0002}, { 0.0000, -0.0000},  {0, 0}},
{{ 0.0000, -0.0000}, { 0.0000, -0.0000}, { 0.0000, -0.0000}, { 0.0000, -0.0000}, { 0.0000, -0.

# BGL

In [21]:
parName = ['a0', 'a1', 'a2', 'b0', 'b1', 'b2', 'c1', 'c2', 'd0', 'd1']
parVal = np.array([0.0320, -0.148, -0.60, 
                   0.01246, 0.0038, 0.02, 
                   # 0.00008, #c0 does not exists in Hammer
                   0.080, -1.11, 
                   0.0526, -0.194])
parSig = np.array([0.0010,  0.031,  0.22, 
                   0.00022, 0.0046, 0.12, 
                   # 0.00094, 
                   0.036, 0.56, 
                   0.0014,  0.043])

In [51]:
corrM = np.array([[ 1.  , -0.75, -0.53,  0.27, -0.17,  0.32,  0.04,  0.14, -0.14,  0.41, -0.23],
                  [-0.75,  1.  ,  0.58,  0.16,  0.21, -0.48,  0.17, -0.29,  0.24, -0.05,  0.28],
                  [-0.53,  0.58,  1.  ,  0.1 , -0.01, -0.2 , -0.3 ,  0.47, -0.43, -0.12,  0.25],
                  [ 0.27,  0.16,  0.1 ,  1.  , -0.05, -0.01,  0.04, -0.09,  0.08,  0.68, -0.01],
                  [-0.17,  0.21, -0.01, -0.05,  1.  , -0.63,  0.35,  0.14, -0.31, -0.19,  0.4 ],
                  [ 0.32, -0.48, -0.2 , -0.01, -0.63,  1.  ,  0.01, -0.25,  0.29,  0.18, -0.37],
                  [ 0.04,  0.17, -0.3 ,  0.04,  0.35,  0.01,  1.  , -0.59,  0.15,  0.21,  0.13],
                  [ 0.14, -0.29,  0.47, -0.09,  0.14, -0.25, -0.59,  1.  , -0.86, -0.21,  0.16],
                  [-0.14,  0.24, -0.43,  0.08, -0.31,  0.29,  0.15, -0.86,  1.  ,  0.13, -0.25],
                  [ 0.41, -0.05, -0.12,  0.68, -0.19,  0.18,  0.21, -0.21,  0.13,  1.  , -0.42],
                  [-0.23,  0.28,  0.25, -0.01,  0.4 , -0.37,  0.13,  0.16, -0.25, -0.42,  1.  ]])
# Remove c2
corrM = corrM[[0,1,2,3,4,5,7,8,9,10]][:,[0,1,2,3,4,5,7,8,9,10]]
eigVal, _ = np.linalg.eig(corrM)
if np.min(eigVal) < 0:
    print 'Correcting non-positve definite correlation matrix by {:1.2e}'.format(np.max(eigVal[eigVal < 0]))
    epsilon = 1e-6
    corrM += np.eye(corrM.shape[0])*(epsilon - np.max(eigVal[eigVal < 0]))
covM = np.atleast_2d(parSig).T * corrM * parSig

Correcting non-positve definite correlation matrix by -6.13e-04


In [52]:
eigVal, eigVec = np.linalg.eig(covM)
eigSig = np.sqrt(eigVal)

[3.26415463e-01 3.89891302e-02 1.34221049e-02 1.51633862e-03
 4.06688041e-04 1.18090561e-05 1.69471857e-06 4.31701496e-07
 6.58832381e-08 2.06350873e-10]


In [54]:
for i in range(eigSig.shape[0]):
    a = np.column_stack((2*eigSig[i]*eigVec[:, i], -2*eigSig[i]*eigVec[:, i]))
    s = '{'
    for l, h in a:
        s += '{{ {:.4f}, {:.4f}}}, '.format(l, h)
    s = s[:-2] + ' },'
    print s

{{ 0.0002, -0.0002}, { -0.0113, 0.0113}, { 0.2153, -0.2153}, { -0.0000, 0.0000}, { 0.0028, -0.0028}, { -0.0738, 0.0738}, { 0.0623, -0.0623}, { -1.1177, 1.1177}, { -0.0004, 0.0004}, { 0.0228, -0.0228} },
{{ 0.0014, -0.0014}, { -0.0495, 0.0495}, { -0.3832, 0.3832}, { -0.0001, 0.0001}, { 0.0013, -0.0013}, { 0.0272, -0.0272}, { -0.0035, 0.0035}, { -0.0756, 0.0756}, { 0.0002, -0.0002}, { -0.0141, 0.0141} },
{{ -0.0006, 0.0006}, { 0.0296, -0.0296}, { -0.0230, 0.0230}, { 0.0000, -0.0000}, { 0.0055, -0.0055}, { -0.2266, 0.2266}, { -0.0024, 0.0024}, { 0.0107, -0.0107}, { -0.0004, 0.0004}, { 0.0281, -0.0281} },
{{ -0.0001, 0.0001}, { 0.0041, -0.0041}, { -0.0025, 0.0025}, { -0.0000, 0.0000}, { 0.0017, -0.0017}, { 0.0104, -0.0104}, { -0.0076, 0.0076}, { -0.0001, 0.0001}, { -0.0010, 0.0010}, { 0.0766, -0.0766} },
{{ 0.0003, -0.0003}, { -0.0191, 0.0191}, { 0.0013, -0.0013}, { -0.0000, 0.0000}, { -0.0018, 0.0018}, { -0.0023, 0.0023}, { 0.0350, -0.0350}, { 0.0026, -0.0026}, { -0.0007, 0.0007}, { 0.004

# B --> D** BLR

From https://arxiv.org/abs/1711.03110 table 5. Narrow states ($D_1$, $D_0^*$, $D_2^*$) are 3/2 isospin doublet and wide states ($D_1^*$) are the 1/2 isospin doublet.

In [16]:
parName = ['t1', 'tp', 'tau1', 'tau2']
parVal = np.array([0.7, -1.6, -0.5, 2.9])
parSig = np.array([0.07, 0.2, 0.3, 1.4])

In [17]:
a = np.zeros((4,4))
a[0, 1] = -0.85
a[0, 2] = 0.53
a[0, 3] = -0.49
a[1, 2] = -0.17
a[1, 3] = 0.086
a[2, 3] = -0.89

corrM = a + a.T + np.identity(a.shape[0])
print corrM

[[ 1.    -0.85   0.53  -0.49 ]
 [-0.85   1.    -0.17   0.086]
 [ 0.53  -0.17   1.    -0.89 ]
 [-0.49   0.086 -0.89   1.   ]]


In [18]:
covM = np.atleast_2d(parSig).T * corrM * parSig
eigVal, eigVec = np.linalg.eig(covM)
eigSig = np.sqrt(eigVal)

In [19]:
for i in range(eigSig.shape[0]):
    a = np.column_stack((eigSig[i]*eigVec[:, i], -eigSig[i]*eigVec[:, i]))
    s = '{'
    for l, h in a:
        s += '{{ {:.4f}, {:.4f}}}, '.format(l, h)
    s += ' {0, 0}, {0, 0}, {0, 0}},'
    print s

{{ 0.0347, -0.0347}, { -0.0185, 0.0185}, { 0.2695, -0.2695}, { -1.3997, 1.3997},  {0, 0}, {0, 0}, {0, 0}},
{{ -0.0569, 0.0569}, { 0.1972, -0.1972}, { -0.0437, 0.0437}, { -0.0124, 0.0124},  {0, 0}, {0, 0}, {0, 0}},
{{ -0.0205, 0.0205}, { -0.0059, 0.0059}, { 0.0004, -0.0004}, { -0.0004, 0.0004},  {0, 0}, {0, 0}, {0, 0}},
{{ -0.0057, 0.0057}, { 0.0274, -0.0274}, { 0.1243, -0.1243}, { 0.0234, -0.0234},  {0, 0}, {0, 0}, {0, 0}},


In [20]:
parName = ['zt1', 'ztp', 'zeta1']
parVal = np.array([0.70, 0.2, 0.6])
parSig = np.array([0.21, 1.4, 0.3])

In [21]:
a = np.zeros((3,3))
a[0, 1] = -0.95
a[0, 2] = -0.44
a[1, 2] = 0.61

corrM = a + a.T + np.identity(a.shape[0])
print corrM

[[ 1.   -0.95 -0.44]
 [-0.95  1.    0.61]
 [-0.44  0.61  1.  ]]


In [22]:
covM = np.atleast_2d(parSig).T * corrM * parSig
eigVal, eigVec = np.linalg.eig(covM)
eigSig = np.sqrt(eigVal)

for i in range(eigSig.shape[0]):
    a = np.column_stack((eigSig[i]*eigVec[:, i], -eigSig[i]*eigVec[:, i]))
    s = '{'
    for l, h in a:
        s += '{{ {:.4f}, {:.4f}}}, '.format(l, h)
    s += ' {0, 0}, {0, 0}},'
    print s

{{ 0.1991, -0.1991}, { -1.3997, 1.3997}, { -0.1873, 0.1873},  {0, 0}, {0, 0}},
{{ -0.0514, 0.0514}, { -0.0084, 0.0084}, { 0.0085, -0.0085},  {0, 0}, {0, 0}},
{{ 0.0427, -0.0427}, { -0.0253, 0.0253}, { 0.2342, -0.2342},  {0, 0}, {0, 0}},
