In [1]:
import numpy as np

# CLN

All number are taken from: https://arxiv.org/pdf/1909.12524.pdf

In [2]:
parName = ['rho2', 'R1', 'R2']
parVal = np.array([1.122, 1.270, 0.852])
parSig = np.array([0.024, 0.026, 0.018])

In [3]:
a = np.zeros((3,3))
a[0, 1] = 0.566
a[0, 2] = -0.824
a[1, 2] = -0.715

corrM = a + a.T + np.identity(3)
print corrM

[[ 1.     0.566 -0.824]
 [ 0.566  1.    -0.715]
 [-0.824 -0.715  1.   ]]


In [4]:
covM = np.atleast_2d(parSig).T * corrM * parSig
print covM

[[ 0.000576    0.00035318 -0.00035597]
 [ 0.00035318  0.000676   -0.00033462]
 [-0.00035597 -0.00033462  0.000324  ]]


In [5]:
eigVal, eigVec = np.linalg.eig(covM)

The normalized (unit “length”) eigenvectors, such that the column v[:,i] is the eigenvector corresponding to the eigenvalue w[i].

In [6]:
eigSig = np.sqrt(eigVal)

In [7]:
for i in range(eigSig.shape[0]):
    print 'eigSigma: {:.3f}'.format(eigSig[i])
    print 'eigVect: {:.3f}, {:.3f}, {:.3f}'.format(*eigVec[:, i])
    a = str(np.column_stack((eigSig[i]*eigVec[:, i], -eigSig[i]*eigVec[:, i])))
    print a.replace('\n', ',').replace('[', '{').replace(']', '}')
    print '\n'

eigSigma: 0.035
eigVect: -0.597, -0.651, 0.469
{{-0.02102485  0.02102485}, {-0.02293032  0.02293032}, { 0.01652843 -0.01652843}}


eigSigma: 0.017
eigVect: -0.664, 0.729, 0.167
{{-0.01105955  0.01105955}, { 0.01215074 -0.01215074}, { 0.00278883 -0.00278883}}


eigSigma: 0.008
eigVect: 0.451, 0.211, 0.867
{{ 0.00341205 -0.00341205}, { 0.00159999 -0.00159999}, { 0.00655998 -0.00655998}}




In [8]:
for i in range(eigSig.shape[0]):
    a = np.column_stack((eigSig[i]*eigVec[:, i], -eigSig[i]*eigVec[:, i]))
    s = '{'
    for l, h in a:
        s += '{{ {:.4f}, {:.4f}}}, '.format(l, h)
    s += ' {0, 0}},'
    print s

{{ -0.0210, 0.0210}, { -0.0229, 0.0229}, { 0.0165, -0.0165},  {0, 0}},
{{ -0.0111, 0.0111}, { 0.0122, -0.0122}, { 0.0028, -0.0028},  {0, 0}},
{{ 0.0034, -0.0034}, { 0.0016, -0.0016}, { 0.0066, -0.0066},  {0, 0}},


In [9]:
for i in range(eigSig.shape[0]):
    a = np.column_stack((2*eigSig[i]*eigVec[:, i], -2*eigSig[i]*eigVec[:, i]))
    s = '{'
    for l, h in a:
        s += '{{ {:.4f}, {:.4f}}}, '.format(l, h)
    s += ' {0, 0}},'
    print s

{{ -0.0420, 0.0420}, { -0.0459, 0.0459}, { 0.0331, -0.0331},  {0, 0}},
{{ -0.0221, 0.0221}, { 0.0243, -0.0243}, { 0.0056, -0.0056},  {0, 0}},
{{ 0.0068, -0.0068}, { 0.0032, -0.0032}, { 0.0131, -0.0131},  {0, 0}},


# BLPR

All references form: arXiv:1703.05330v4

Using scheme NoL+SR (No Lattice QCD, Yes QCD sum rules)

In [10]:
# RhoSq, chi2(1), chi2(1)prime, chi3(1)prime, eta(1), eta(1)prime, V20
parName = ['RhoSq','chi21','chi2p','chi3p','eta1','etap','dV20']
parVal = np.array([1.19, -0.06, -0.00, 0.04, 0.35, -0.11, 0.])
parSig = np.array([0.08, 0.02, 0.02, 0.02, 0.14, 0.18, 0.0001])

In [11]:
a = np.zeros((len(parName),len(parName)))
a[0, 1] = -0.15
a[0, 2] = -0.07
a[0, 3] = 0.57
a[0, 4] = 0.44
a[0, 5] = -0.11

a[1, 2] = -0.02
a[1, 3] = 0.07
a[1, 4] = -0.15
a[1, 5] = -0.09

a[2, 3] = 0.03
a[2, 4] = -0.07
a[2, 5] = -0.05

a[3, 4] = 0.17
a[3, 5] = 0.16

a[4, 5] = -0.40

corrM = a + a.T + np.identity(len(parName))
print corrM

[[ 1.   -0.15 -0.07  0.57  0.44 -0.11  0.  ]
 [-0.15  1.   -0.02  0.07 -0.15 -0.09  0.  ]
 [-0.07 -0.02  1.    0.03 -0.07 -0.05  0.  ]
 [ 0.57  0.07  0.03  1.    0.17  0.16  0.  ]
 [ 0.44 -0.15 -0.07  0.17  1.   -0.4   0.  ]
 [-0.11 -0.09 -0.05  0.16 -0.4   1.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    1.  ]]


In [12]:
covM = np.atleast_2d(parSig).T * corrM * parSig
print covM

[[ 6.400e-03 -2.400e-04 -1.120e-04  9.120e-04  4.928e-03 -1.584e-03
   0.000e+00]
 [-2.400e-04  4.000e-04 -8.000e-06  2.800e-05 -4.200e-04 -3.240e-04
   0.000e+00]
 [-1.120e-04 -8.000e-06  4.000e-04  1.200e-05 -1.960e-04 -1.800e-04
   0.000e+00]
 [ 9.120e-04  2.800e-05  1.200e-05  4.000e-04  4.760e-04  5.760e-04
   0.000e+00]
 [ 4.928e-03 -4.200e-04 -1.960e-04  4.760e-04  1.960e-02 -1.008e-02
   0.000e+00]
 [-1.584e-03 -3.240e-04 -1.800e-04  5.760e-04 -1.008e-02  3.240e-02
   0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00
   1.000e-08]]


In [13]:
eigVal, eigVec = np.linalg.eig(covM)
eigSig = np.sqrt(eigVal)

In [14]:
for i in range(eigSig.shape[0]):
    print 'eigSigma: {:.3f}'.format(eigSig[i])
    print 'eigVect: {:.3f}, {:.3f}, {:.3f}'.format(*eigVec[:, i])
    a = str(np.column_stack((eigSig[i]*eigVec[:, i], -eigSig[i]*eigVec[:, i])))
    a = a.replace('\n', ',').replace('[', '{').replace(']', '}')
    i = 0
    while i < len(a):
        if a[i].isdigit():
            if a[i+1] == ' ':
                a = a[:i+1] + ',' + a[i+1:]
                i += 2
            else:
                i += 1
        else:
            i += 1
    print a+','
    print '\n'

eigSigma: 0.196
eigVect: 0.119, 0.001, 0.001
{{ 0.02322283, -0.02322283}, { 0.00022429, -0.00022429}, { 0.00023267, -0.00023267}, {-0.00079148,  0.00079148}, { 0.09664184, -0.09664184}, {-0.16885149,  0.16885149}, { 0.         -0.        }},


eigSigma: 0.124
eigVect: -0.349, 0.038, 0.019
{{-0.04345272,  0.04345272}, { 0.00474643, -0.00474643}, { 0.00233232, -0.00233232}, {-0.00809314,  0.00809314}, {-0.09813503,  0.09813503}, {-0.06209618,  0.06209618}, { 0.         -0.        }},


eigSigma: 0.069
eigVect: 0.916, -0.008, -0.003
{{ 0.06298508, -0.06298508}, {-0.00056467,  0.00056467}, {-0.00022681,  0.00022681}, { 0.00975046, -0.00975046}, {-0.02509061,  0.02509061}, {-0.00574474,  0.00574474}, { 0.         -0.        }},


eigSigma: 0.014
eigVect: 0.148, 0.395, 0.196
{{ 0.002127,   -0.002127,  }, { 0.00565397, -0.00565397}, { 0.00281448, -0.00281448}, {-0.01267561,  0.01267561}, { 0.0001571,  -0.0001571, }, { 0.00045325, -0.00045325}, { 0.         -0.        }},


eigSigma: 0.020
eig